### ISSUE TITLE
Ailments

### ISSUE THREAD

**Issue by andyweiss1982** [lorijustlori/Guide-the-Patient#1]
https://github.com/lorijustlori/Guide-the-Patient/blob/0dcb03911a22790706ca8c56bd9f3315280ec924/db/schema.rb#L17

Should ailments have descriptions -- or names?   Description to me sounds like something longer.

Also, `code` and `description/name` should have validations, unique indices, and constraints.   Probably both values need to be present and also unique.

**Comment by lorijustlori** [comment]
class Ailment < ApplicationRecord
	validates :code, :description, 	presence: true,
									uniqueness: true,
									value: true
end
