### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by andyweiss1982** [lorijustlori/Guide-the-Patient#13]
https://github.com/lorijustlori/Guide-the-Patient/blob/321d46d6e8c2559a5bc65a3c55fcc1de1a65fc3f/app/models/ailment.rb#L2

`presence`, not `presense`

**Comment by lorijustlori** [comment]
class Ailment < ApplicationRecord
	validates :code, :description, 	presence: true,
									uniqueness: true,
									value: true
end

**Comment by lorijustlori** [comment]
closed #13
