### ISSUE TITLE
uniqueness scope

### ISSUE THREAD

**Issue by andyweiss1982** [lorijustlori/Guide-the-Patient#14]
https://github.com/lorijustlori/Guide-the-Patient/blob/321d46d6e8c2559a5bc65a3c55fcc1de1a65fc3f/app/models/hospital.rb#L6

should be `{scope: [:city, :state]} `

**Comment by lorijustlori** [comment]
validates :address, uniqueness: { scope: [:city, :state]}

**Comment by lorijustlori** [comment]
closed #14
