### ISSUE TITLE
Hospitals

### ISSUE THREAD

**Issue by andyweiss1982** [lorijustlori/Guide-the-Patient#2]
https://github.com/lorijustlori/Guide-the-Patient/blob/0dcb03911a22790706ca8c56bd9f3315280ec924/db/schema.rb#L22

These need presence validations and not null constraints at a minimum.   You probably also want to have a unique index / validation to show that the entire Combination of name / address / etc is unique.  (for example, there may be 2 Mercy hospitals, or even 2 Mt sinai's in Miami, but there should't be 2 Doctor's Hospital as 123 Lane in Alexandria VA).

See: https://stackoverflow.com/questions/34424154/rails-validate-uniqueness-of-two-columns-together/34424237

**Comment by lorijustlori** [comment]
class Hospital < ApplicationRecord
	has_many :physicians

	validates :name, presense: true 
					 :null => false
	validates :address, uniqueness: { scope: :state }
end
