### ISSUE TITLE
Remedies

### ISSUE THREAD

**Issue by andyweiss1982** [lorijustlori/Guide-the-Patient#3]
https://github.com/lorijustlori/Guide-the-Patient/blob/0dcb03911a22790706ca8c56bd9f3315280ec924/db/schema.rb#L52

See my comment on ailments.  I think all of the above applies to remedies as well.

**Comment by lorijustlori** [comment]
class Remedy < ApplicationRecord
	validates :code, :description, 	presence: true,
									uniqueness: true,
									value: true
end
