### ISSUE TITLE
Patient

### ISSUE THREAD

**Issue by andyweiss1982** [lorijustlori/Guide-the-Patient#4]
https://github.com/lorijustlori/Guide-the-Patient/blob/0dcb03911a22790706ca8c56bd9f3315280ec924/db/schema.rb#L32

Record number and email both need to be present and unique (model validation and db index plus not null)
The rest of the fields should just be not null (and presence model validation)

**Comment by lorijustlori** [comment]
class Patient < ApplicationRecord

	validates :medical_record_number, :email,   presence: true,
												uniqueness: true
												:null => false
				:first_name, :last_name, :address, :city, :state, :phone,
					:null => false									
end
