### ISSUE TITLE
Physicians

### ISSUE THREAD

**Issue by andyweiss1982** [lorijustlori/Guide-the-Patient#5]
https://github.com/lorijustlori/Guide-the-Patient/blob/0dcb03911a22790706ca8c56bd9f3315280ec924/db/schema.rb#L45

Presence validations and not null constraints on the name fields.   Also `belongs_to` hospital (hospital `has_many` physicians)

**Comment by lorijustlori** [comment]
class Hospital < ApplicationRecord
	has_many :physicians
end

class Physician < ApplicationRecord
	belongs_to :hospital
end

class Ailment < ApplicationRecord
	validates :code, :description, 	presence: true,
									uniqueness: true,
									value: true
end
